var name1, name2, name3, name4, name5;
name1 = "Fuwad";
name2 = "Akashi";
name3 = "Rafiq";
name4 = "Sowrav";
name5 = "Izhan";
//console.log(name5);
var names = new Array(5);
names[0] = "Fuwad";
names[1] = "Akashi";
names[2] = "Rafiq";
names[3] = "Sowrav";
names[4] = "Izhan";
console.log(names.length);
var names = ["Fuwad","Akashi","ovi","Sowrav","Izhan"];
console.log(names. length);
console.log(names);
console.log(names[4]);
names.push("Mamun");
console.log(names);
console.log(names[5]);
names.push("Moyna");
names.push("Jannat");
names.push("Hazi");
console.log(names. length);
console.log(names[8]);
names.pop();
console.log(names);
names.pop();
console.log(names);
var country1 = ["Bangladesh","india"];
var country2 = ["Ireland","Netherland"];
var country = country1.concat(country2);
console.log(country);
